Heads:
  Pacman:
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQyYWE1ZTMxODQ2NThkNDc1MTFjZWEyOGRkYjVjNDFhMzgwYjgwYTQzNzdjMThjM2M1NWJjOWU4ZTVjNjRjIn19fQ=="
    name: "&cPacMan"
    permission: false
    lore:
    - "PacMan"
    - "Test"

Names:
  - "Pacman"

mysql:
  enabled: false
  host: localhost
  port: 3306
  database: createhead
  username: root
  password: password
  table: createhead_data
  use-ssl: false

ru:
  text-not-permission: "&cУ вас нет прав"
  text-reload-success: "&aКонфигурация и MySQL успешно перезагружены."
  text-head-not-found: "&cГолова не найдена в конфигурации."
  text-gui-open-permission: "Выдать permission"
  text-gui-close-permission: "Отнять permission"
